Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NTLBookStore.Data;
using NTLBookStore.ViewModels;

namespace NTLBookStore.Controllers;

public class BooksController : Controller
{
    private readonly NTLBookStoreContext _context;

    public BooksController(NTLBookStoreContext context)
    {
        _context = context;
    }

    // GET: Books
    public async Task<IActionResult> Index(SearchViewModel? model)
    {
        var query = _context.Books
            .Include(b => b.Category)
            .Include(b => b.Image)
            .AsQueryable();

        if (model != null && !string.IsNullOrWhiteSpace(model.KeyWord))
        {
            var keyword = model.KeyWord.Trim().ToLower();
            query = query.Where(b => b.Title.ToLower().Contains(keyword)
                                     || b.Category.Name.ToLower().Contains(keyword));
        }

        return View(await query.ToListAsync());
    }

    // GET: Books/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Books == null)
        {
            return NotFound();
        }

        var book = await _context.Books
            .Include(b => b.Category)
            .Include(b => b.Store)
            .Include(b => b.Image)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (book == null)
        {
            return NotFound();
        }

        return View(book);
    }
    // GET: Books/SearchByBook
    public IActionResult SearchByBook(string keyword)
    {
        if (string.IsNullOrEmpty(keyword))
        {
            return RedirectToAction(nameof(Index));
        }

        var books = _context.Books
            .Include(b => b.Category)
            .Include(b => b.Image)
            .Where(b => b.Title.ToLower().Contains(keyword.ToLower()))
            .ToList();

        var model = new SearchViewModel
        {
            KeyWord = keyword,
            Books = books
        };

        return View("SearchResult", model);
    }

// GET: Books/SearchByCategory
    public IActionResult SearchByCategory(string category)
    {
        if (string.IsNullOrEmpty(category))
        {
            return RedirectToAction(nameof(Index));
        }

        var books = _context.Books
            .Include(b => b.Category)
            .Include(b => b.Image)
            .Where(b => b.Category.Name.ToLower() == category.ToLower())
            .ToList();

        var model = new SearchViewModel
        {
            BookCategory = category,
            Books = books
        };

        return View("SearchResult", model);
    }

    public IActionResult Help()
    {
        return View();
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NTLBookStore.Data;
using NTLBookStore.Models;
using NTLBookStore.ViewModels;

namespace NTLBookStore.Controllers;

    [Authorize]
    public class CartController : Controller
    {
        private readonly NTLBookStoreContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public CartController(NTLBookStoreContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        private string? _customerId;

        private string CustomerId
        {
            get
            {
                _customerId ??= userManager.GetUserId(User);
                return _customerId;
            }
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var items = await context.CartItems
                .Include(ci => ci.Book)
                .Where(ci => ci.CustomerId == CustomerId)
                .ToListAsync();
            return View(items);
        }

        // GET: Carts/Create
        public async Task<IActionResult> AddItem(int? bookId, int quantity = 1)
        {
            if (bookId == null || quantity <= 0)
                return BadRequest();

            var book = await context.Books.FindAsync(bookId);

            if (book == null)
                return BadRequest();

            var item = await context.CartItems
                .FirstOrDefaultAsync(ci => ci.CustomerId == CustomerId && ci.BookId == book.Id);

            if (item == null)
            {
                item = new()
                {
                    CustomerId = CustomerId,
                    BookId = book.Id,
                    Quantity = quantity,
                };
                context.CartItems.Add(item);
            }
            else
            {
                item.Quantity += quantity;
            }

            await context.SaveChangesAsync();

            return Ok(item);
        }

        public async Task<IActionResult> Checkout()
        {
            var customer = await userManager.GetUserAsync(User);

            if (customer == null)
                return Unauthorized();

            var orders = await context.CartItems
                .Include(ci => ci.Book)
                .Where(ci => ci.CustomerId == customer.Id)
                .GroupBy(ci => ci.Book.StoreId)
                .Select(g => new Order(CustomerId, g.Key, g.ToList()))
                .ToListAsync();

            foreach (var order in orders)
            {
                order.Store = await context.Stores
                .AsNoTracking()
                .FirstAsync(s => s.Id == order.StoreId);
            };

            var model = new CheckoutViewModel()
            {
                Orders = orders,
                Name = customer.FullName,
                Address = customer.HomeAddress,
                PhoneNumber = customer.PhoneNumber,
            };

            return View(model);
        }

        [HttpPost, ActionName("Checkout")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CheckoutConfirm(CheckoutViewModel model)
        {
            var customer = await userManager.GetUserAsync(User);
            if (customer == null)
                return Unauthorized();

            List<Order> orders;
            if (!ModelState.IsValid)
            {
                orders = await context.CartItems
                    .Include(ci => ci.Book)
                    .Where(ci => ci.CustomerId == customer.Id)
                    .GroupBy(ci => ci.Book.StoreId)
                    .Select(g => new Order(customer.Id, g.Key, g.ToList()))
                    .ToListAsync();

                foreach (var order in orders)
                {
                    order.Store = await context.Stores
                    .AsNoTracking()
                    .FirstAsync(s => s.Id == order.StoreId);
                };

                model.Orders = orders;

                return View(model);
            }

            var items = await context.CartItems
                .Include(ci => ci.Book)
                .Where(ci => ci.CustomerId == customer.Id)
                .ToListAsync();

            orders = items.GroupBy(ci => ci.Book.StoreId, (storeId, items) => new Order(customer.Id, storeId, items)
            {
                FullName = model.Name,
                Address = model.Address,
                PhoneNumber = model.PhoneNumber,
            })
                .ToList();

            context.CartItems.RemoveRange(items);
            context.AddRange(orders);

            await context.SaveChangesAsync();

            return View("CheckoutSuccess");
        }

        public async Task<IActionResult> RemoveItem(int? bookId, int? quantity)
        {
            if (bookId == null || quantity <= 0)
                return BadRequest();

            var item = await context.CartItems
                .FirstOrDefaultAsync(ci => ci.CustomerId == CustomerId && ci.BookId == bookId);

            if (item == null)
                return Ok();

            if (quantity == null)
            {
                context.CartItems.Remove(item);
            }
            else
            {
                if (item.Quantity > quantity)
                    item.Quantity -= quantity.Value;
                else item.Quantity = 1;
            }
            await context.SaveChangesAsync();

            return Ok(item);
        }
    }
    
    
    

Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NTLBookStore.Data;
using NTLBookStore.Helpers;
using NTLBookStore.Models;

namespace NTLBookStore.Controllers;

[Authorize(Roles = Roles.User)]
public class OrdersController : Controller
{
    private readonly NTLBookStoreContext context;
    private readonly UserManager<ApplicationUser> userManager;

    public OrdersController(NTLBookStoreContext context, UserManager<ApplicationUser> userManager)
    {
        this.context = context;
        this.userManager = userManager;
    }

    private string? _customerId;

    private string CustomerId
    {
        get
        {
            _customerId ??= userManager.GetUserId(User);
            return _customerId;
        }
    }

    // GET: Orders
    public async Task<IActionResult> Index()
    {
        var orders = await context.Orders
            .Include(o => o.Store)
            .Where(o => o.CustomerId == CustomerId)
            .ToListAsync();
        return View(orders);
    }

    // GET: Orders/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var order = await context.Orders
            .Include(o => o.Store)
            .Include(o => o.OrderItems)
            .ThenInclude(oi => oi.Book)
            .FirstOrDefaultAsync(m => m.Id == id);

        if (order == null || order.CustomerId != CustomerId)
        {
            return NotFound();
        }

        order.Customer = await userManager.FindByIdAsync(CustomerId);

        return View(order);
    }
}

Views/Shared/_Layout.cshtml
@{
    // Layout = "_Layout";
    SearchViewModel model = SearchViewModel.BookSearchViewModel;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - NTLBookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/home.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/NTLBookStore.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="../wwwroot/css/Test.css" asp-append-version="true"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@500&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <div class="hero">
        <div class="container">
            <nav>
                <a href="" id="logo">FPT BOOK</a>
                <ul>
                    <li><a class="nav-item" asp-area="" asp-controller="Books" asp-action="Index">Book</a></li>
                    
                   
                     @if (User.IsInRole(Roles.StoreOwner))
                     {
                         <li class="nav-item">
                             <a class="nav-item" asp-area="StoreOwner" asp-controller="Store" asp-action="Index">Store</a>
                         </li>
                         <li class="nav-item">
                             <a class="nav-item" asp-area="StoreOwner" asp-controller="Books" asp-action="Index">Store Books</a>
                         </li>
                         <li class="nav-item">
                             <a class="nav-item" asp-area="StoreOwner" asp-controller="Orders" asp-action="Index">Orders</a>
                         </li>
                         <li class="nav-item">
                             <a class="nav-item" asp-area="StoreOwner" asp-controller="RequestCategories" asp-action="Index">Requests New Category</a>
                         </li>
                     }
                    @if (User.IsInRole(Roles.Admin))
                    {
                        <li class="nav-item">
                            <a class="nav-item" asp-area="Admin" asp-controller="RequestCategories" asp-action="Index">Requests New Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item" asp-area="Admin" asp-controller="Accounts" asp-action="Index">Account List</a>
                        </li>
                    }
                    @if (User.IsInRole(Roles.User))
                    {
                        <li><a class="nav-item" id="help_item" asp-area="" asp-controller="Books" asp-action="Help">Help</a></li>
                        <li class="nav-item">
                            <a class="nav-item"id="orders_item" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <form class="form-inline">
                            <li class="nav-item">
                                <partial name="_SearchPartial" model="model" />
                                @*<button class="btn btn-outline-success my-2 my-sm-0" id="search_button" type="submit">Search</button>*@
                            </li>
                        </form>
                        
                    }
                     @if (User.Identity?.IsAuthenticated is false or null || User.IsInRole(Roles.User))
                     {
                         <div class="nav-item">
                             <a class="nav-item" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                         </div>
                     }
                     <partial name="_LoginPartial"/>
                </ul>
                

                @*<button type="button" onclick="toggleBtn()" id="btn"><span></span></button>*@
            </nav>
            
        </div>
        
        @*<div class="lamp-container">
            <img src="img/images/lamp.png" alt="lamp" class="lamp">
            <img src="img/images/light.png" alt="light" class="light" id="light">
        </div>
        <div class="text-container">
            <h1>"Light up" the souls who love books</h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            <a href="">Check All Products</a>
        </div>*@
    </div>
    @*--------------------------*@
    @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppDev</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                    </li>
                    @if (User.IsInRole(Roles.StoreOwner))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="StoreOwner" asp-controller="Store" asp-action="Index">Store</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="StoreOwner" asp-controller="Books" asp-action="Index">Store Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="StoreOwner" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="StoreOwner" asp-controller="RequestCategories" asp-action="Index">Requests New Category</a>
                        </li>
                    }
                    @if (User.IsInRole(Roles.Admin))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="RequestCategories" asp-action="Index">Requests New Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Accounts" asp-action="Index">Accounts</a>
                        </li>
                    }
                    @if (User.IsInRole(Roles.User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>

                    }
                </ul>
                @if (User.Identity?.IsAuthenticated is false or null || User.IsInRole(Roles.User))
                {
                    <div class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                    </div>
                }
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>*@
    <div class="container-md justify-content-center">
        @await RenderSectionAsync("Search", required: false)
    </div>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<div class="">
    <!----------- Footer ------------>
    <footer class="footer-bs">
        <div class="container">
            <div class="row">
                <div class="col-md-3 footer-brand animated">
                    <h2>FPT BOOK</h2>
                    <p>Suspendisse hendrerit tellus laoreet luctus pharetra. Aliquam porttitor vitae orci nec ultricies. Curabitur vehicula, libero eget faucibus faucibus, purus erat eleifend enim, porta pellentesque ex mi ut sem.</p>
                    <p>© 2014 BS3 UI Kit, All rights reserved</p>
                </div>
                <div class="col-md-4 footer-nav animated fadeInUp">
                    <h4>Menu —</h4>
                    <div class="col-md-6">
                        <ul class="pages">
                            <li><a href="#">Travel</a></li>
                            <li><a href="#">Nature</a></li>
                            <li><a href="#">Explores</a></li>
                            <li><a href="#">Science</a></li>
                            <li><a href="#">Advice</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Contacts</a></li>
                            <li><a href="#">Terms & Condition</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-2 footer-social animated fadeInDown">
                    <h4>Follow Us</h4>
                    <ul>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Instagram</a></li>
                        <li><a href="#">RSS</a></li>
                    </ul>
                </div>
                <div class="col-md-3 footer-ns animated fadeInRight">
                    <h4>Newsletter</h4>
                    <p>A rover wearing a fuzzy suit doesn’t alarm the real penguins</p>
                </div>
            </div>
            
        </div>
    </footer>


</div>
@*<script>
    var btn = document.getElementById("btn");
    var light = document.getElementById("light");
    function toggleBtn(){
        btn.classList.toggle("active");
        light.classList.toggle("on");
    }
</script>*@
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutWithSearch.cshtml
@{
    Layout = "_Layout";
    SearchViewModel model = SearchViewModel.BookSearchViewModel;
}
@RenderBody()
@section Scripts{
    @await RenderSectionAsync("Scripts", required: false)

}

Views/Shared/_SearchPartial.cshtml
@model SearchViewModel



<form method="get" action="@Model?.Action">
    <input asp-for="Type" type="hidden" />
    <input asp-for="KeyWord" class="form-control" id="search_form" placeholder="Searching..." />
    <button class="btn btn-primary my-2 my-sm-0" id="search_button" type="submit">Search</button>
</form>